### PR TITLE
Removes apparently obsolete files.

### PR DESCRIPTION
**Pull request by christian-schlichtherle**

### CODE REVIEW

**Comment by christian-schlichtherle** [comment]
It seems to me as the original files have been renamed.

**Comment by christian-schlichtherle** [comment]
?

**Comment by JustDerb** [comment]
> It seems to me that the original files have been renamed.

Correct. But this pull request looks to delete the files outright and not rename them. I'd take this pull request if these files where renamed (and possibly updated).

**Comment by JustDerb** [comment]
I've gone ahead and updated to 18.02.22 (using the [generator](https://github.com/JustDerb/yed-aws-palettes/tree/master/generator)), so everything should be up to date. I'm closing this PR because of this.

**Comment by christian-schlichtherle** [comment]
thanks!

**Pull request closed without merging**
